### ISSUE TITLE
TryMeasureBootConfig should measure file contents, not names

### ISSUE THREAD

**Issue by insomniacslk** [systemboot/systemboot#90]
`TryMeasureBootConfig` in `pkg/crypto` at the moment is measuring file names instead of file contents. This must be fixed.

https://github.com/systemboot/systemboot/blob/72475fe18864ddaffb9b8a1136dbae665ab17abe/pkg/crypto/measure.go#L28

**Comment by zaolin** [comment]
Not true, there is a measure files function. In general it should measure the config as well. My fault not pointing that out

**Comment by insomniacslk** [comment]
Dang, I didn't see the call to `TryMeasureFiles` at the end, sorry for opening this issue unnecessarily!
